### PR TITLE
Fix activity context not being available in logger

### LINKED ISSUE #5: Tracing context is not available when errors are logged
This means that our centralized logging doesn't correlate the error with the trace correctly, and thus we have a really hard time finding the actual error when something goes haywire.

### PR DESCRIPTION
**Pull request by zlepper**
Fixes #5

### CODE REVIEW

File: Rebus.Diagnostics/Config/DiagnosticSourcesConfigurationExtensions.cs [hunk 1]
```diff
@@ -23,14 +23,15 @@ public static void EnableDiagnosticSources(this OptionsConfigurer configurer)
...
-                    typeof(DeserializeIncomingMessageStep));
 
                 var invokerWrapper = new IncomingDiagnosticsHandlerInvokerWrapper();
                 injector.OnReceive(invokerWrapper, PipelineRelativePosition.After, typeof(ActivateHandlersStep));
+
+                var concatenator = new PipelineStepConcatenator(injector);
+                concatenator.OnReceive(incomingStep, PipelineAbsolutePosition.Front);
                 
-                return injector;
+                return concatenator;
```
Comment (zlepper) [inline Rebus.Diagnostics/Config/DiagnosticSourcesConfigurationExtensions.cs:33]: I'm honestly not sure if this is the best way to go about things, but it does at least fix the issue.

Comment (mookid8000) [reply Rebus.Diagnostics/Config/DiagnosticSourcesConfigurationExtensions.cs:33]: Cannot see why this would cause any trouble 🙂 looks fine to me

**Review by mookid8000 — APPROVED** [review]

**Comment by mookid8000** [comment]
Excellent 👍 it's on NuGet.org as Rebus.OpenTelemetry 0.0.3
